name: Auto-publish weekly (Sunday 12:00 London)
on:
  schedule:
    - cron: "0 11 * * 0"   # Sun 12:00 during BST
    - cron: "0 12 * * 0"   # Sun 12:00 during GMT
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: weekly-publish
  cancel-in-progress: false
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find latest draft
        id: find
        run: |
          DRAFT=$(ls -t _drafts/*-the-corporate-brief.md 2>/dev/null | head -n1 || true)
          echo "draft=$DRAFT" >> $GITHUB_OUTPUT
          if [ -z "$DRAFT" ]; then
            echo "No draft present; exiting."; exit 0
          fi
      - name: Skip if human edited
        run: |
          DRAFT="${{ steps.find.outputs.draft }}"
          AUTHORS=$(git log --pretty='%an' -- "$DRAFT" || true | sort -u)
          echo "Authors:"; echo "$AUTHORS"
          if echo "$AUTHORS" | grep -qv "github-actions"; then
            echo "Human edits found; skipping auto-publish."; exit 0
          fi
      - name: Promote draft to posts
        run: |
          DRAFT="${{ steps.find.outputs.draft }}"
          WEEK=$(echo "$DRAFT" | sed -E 's#.*week-([0-9]{2}).*#\1#')
          DATE=$(python - <<'PY'
from datetime import datetime
from zoneinfo import ZoneInfo
print(datetime.now(ZoneInfo("Europe/London")).strftime("%Y-%m-%d"))
PY
)
          DEST="_posts/${DATE}-week-${WEEK}-the-corporate-brief.md"
          git mv "$DRAFT" "$DEST"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto-publish Week ${WEEK} brief"
          git push
